# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ImageSearcher
                                 A QGIS plugin
 A pseudo-google lens image search
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-01-07
        copyright            : (C) 2023 by NA
        email                : dak.boniface@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ImageSearcher class from file ImageSearcher.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .image_searcher import ImageSearcher
    return ImageSearcher(iface)
